// ─────────────────────────────────────────────────────────────────────────────
//  masterdata.js — Central seed data for the Master module
//  Contains: SEEDED_KARIGARS, SEEDED_ITEMS
// ─────────────────────────────────────────────────────────────────────────────

// ── Karigar Details Seed Data ─────────────────────────────────────────────────
export const SEEDED_KARIGARS = [
  { id: 'KR-001', name: 'Ramesh Kumar',   number: '9801234567', address: 'Shop 12, Zaveri Bazaar, Mumbai',     type: 'Office'  },
  { id: 'KR-002', name: 'Suresh Patel',   number: '9802234567', address: 'Factory 3, MIDC, Thane',            type: 'Factory' },
  { id: 'KR-003', name: 'Amit Shah',      number: '9803234567', address: 'Office 7, Opera House, Mumbai',     type: 'Office'  },
  { id: 'KR-004', name: 'Rahul Verma',    number: '9804234567', address: 'Unit 5, Bhiwandi Industrial Area',  type: 'Factory' },
  { id: 'KR-005', name: 'Manoj Tiwari',   number: '9805234567', address: 'Shop 4, Crawford Market, Mumbai',   type: 'Office'  },
  { id: 'KR-006', name: 'Prakash Joshi',  number: '9806234567', address: 'Shed 9, Taloja MIDC, Navi Mumbai',  type: 'Factory' },
  { id: 'KR-007', name: 'Deepak Gupta',   number: '9807234567', address: 'Room 2, Dharavi Crafts Centre',     type: 'Office'  },
  { id: 'KR-008', name: 'Sanjay Mehta',   number: '9808234567', address: 'Workshop 6, Kalbadevi, Mumbai',     type: 'Factory' },
  { id: 'KR-009', name: 'Dinesh Sharma',  number: '9809234567', address: 'Office 3, Lalbaug, Mumbai',         type: 'Office'  },
  { id: 'KR-010', name: 'Vikram Singh',   number: '9810234567', address: 'Plot 11, Turbhe MIDC, Navi Mumbai', type: 'Factory' },
  { id: 'KR-011', name: 'Ajay Yadav',     number: '9811234567', address: 'Shop 8, Masjid Bunder, Mumbai',     type: 'Office'  },
  { id: 'KR-012', name: 'Ravi Dubey',     number: '9812234567', address: 'Factory 2, Ambernath East',         type: 'Factory' },
  { id: 'KR-013', name: 'Pradeep Nair',   number: '9813234567', address: 'Shop 5, Bhuleshwar, Mumbai',        type: 'Office'  },
  { id: 'KR-014', name: 'Santosh Kadam',  number: '9814234567', address: 'Shed 14, Dombivli MIDC',            type: 'Factory' },
  { id: 'KR-015', name: 'Vijay Patil',    number: '9815234567', address: 'Office 9, Charni Road, Mumbai',     type: 'Office'  },
  { id: 'KR-016', name: 'Naveen Jain',    number: '9816234567', address: 'Shop 11, Byculla, Mumbai',          type: 'Office'  },
  { id: 'KR-017', name: 'Hemant Rao',     number: '9817234567', address: 'Unit 8, Kalyan Industrial Zone',    type: 'Factory' },
  { id: 'KR-018', name: 'Girish Pandey',  number: '9818234567', address: 'Office 5, Dadar, Mumbai',           type: 'Office'  },
  { id: 'KR-019', name: 'Sunil Bansode',  number: '9819234567', address: 'Factory 7, Vasai East MIDC',        type: 'Factory' },
  { id: 'KR-020', name: 'Arun Deshmukh',  number: '9820234567', address: 'Shop 3, Kurla Market, Mumbai',      type: 'Office'  },
];

// ── Items / Inventory Seed Data ───────────────────────────────────────────────
export const SEEDED_ITEMS = [
  { code: 'IT-001', name: 'Screwdriver Set 12pcs', brand: 'Bosch', category: 'Hardware & Tools', price: 850 },
  { code: 'IT-002', name: 'Circuit Breaker 16A', brand: 'Schneider', category: 'Electrical Supplies', price: 320 },
  { code: 'IT-003', name: 'A4 Copier Paper (Rim)', brand: 'HP', category: 'Office Stationery', price: 280 },
  { code: 'IT-004', name: 'N95 Safety Mask', brand: '3M', category: 'Safety Gear', price: 45 },
  { code: 'IT-005', name: 'TMT Steel Rod 12mm', brand: 'Tata Steel', category: 'Raw Materials', price: 550 },
  { code: 'IT-006', name: 'LED Tube Light 20W', brand: 'Philips', category: 'Electrical Supplies', price: 180 },
  { code: 'IT-007', name: 'PVC Conduit Pipe 25mm', brand: 'Supreme', category: 'Plumbing Parts', price: 75 },
  { code: 'IT-008', name: 'Ball Valve 1 Inch', brand: 'Supreme', category: 'Plumbing Parts', price: 240 },
  { code: 'IT-009', name: 'Safety Goggles Clear', brand: '3M', category: 'Safety Gear', price: 120 },
  { code: 'IT-010', name: 'Electrical Tape Black', brand: 'Anchor', category: 'Electrical Supplies', price: 25 },
  { code: 'IT-011', name: 'Angle Grinder 4-Inch', brand: 'Bosch', category: 'Hardware & Tools', price: 2450 },
  { code: 'IT-012', name: 'Impact Drill 13mm', brand: 'Bosch', category: 'Hardware & Tools', price: 3800 },
  { code: 'IT-013', name: 'Digital Multimeter', brand: 'Schneider', category: 'Electrical Supplies', price: 1200 },
  { code: 'IT-014', name: 'Permanent Markers (Black)', brand: 'HP', category: 'Office Stationery', price: 90 },
  { code: 'IT-015', name: 'High-Visibility Safety Vest', brand: '3M', category: 'Safety Gear', price: 150 },
  { code: 'IT-016', name: 'Galvanized Iron Wire 2mm', brand: 'Tata Steel', category: 'Raw Materials', price: 110 },
  { code: 'IT-017', name: 'LED Bulb 9W E27', brand: 'Philips', category: 'Electrical Supplies', price: 95 },
  { code: 'IT-018', name: 'Teflon Pipe Sealant Tape', brand: 'Supreme', category: 'Plumbing Parts', price: 15 },
  { code: 'IT-019', name: 'Hammer Drill Bit Set', brand: 'Bosch', category: 'Hardware & Tools', price: 950 },
  { code: 'IT-020', name: 'Switch Socket Combo 16A', brand: 'Anchor', category: 'Electrical Supplies', price: 140 },
  { code: 'IT-021', name: 'Steel Measuring Tape 5m', brand: 'Bosch', category: 'Hardware & Tools', price: 290 },
  { code: 'IT-022', name: 'Distribution Board 8-Way', brand: 'Schneider', category: 'Electrical Supplies', price: 1150 },
  { code: 'IT-023', name: 'Wireless Mouse', brand: 'HP', category: 'Office Stationery', price: 650 },
  { code: 'IT-024', name: 'Leather Safety Gloves', brand: '3M', category: 'Safety Gear', price: 350 },
  { code: 'IT-025', name: 'Binding Wire 18 Gauge', brand: 'Tata Steel', category: 'Raw Materials', price: 98 },
  { code: 'IT-026', name: 'LED Floodlight 50W', brand: 'Philips', category: 'Electrical Supplies', price: 1450 },
  { code: 'IT-027', name: 'CPVC Solvent Cement 250ml', brand: 'Supreme', category: 'Plumbing Parts', price: 190 },
  { code: 'IT-028', name: 'Gate Valve Brass 1.5"', brand: 'Supreme', category: 'Plumbing Parts', price: 580 },
  { code: 'IT-029', name: 'Ear Plugs Polyurethane', brand: '3M', category: 'Safety Gear', price: 12 },
  { code: 'IT-030', name: 'Modular Switch 6A Pack of 10', brand: 'Anchor', category: 'Electrical Supplies', price: 220 },
  { code: 'IT-031', name: 'Hand Hacksaw Frame 12"', brand: 'Bosch', category: 'Hardware & Tools', price: 420 },
  { code: 'IT-032', name: 'Copper Wire Reel 1.5 sqmm', brand: 'Anchor', category: 'Electrical Supplies', price: 1850 },
  { code: 'IT-033', name: 'Scientific Calculator', brand: 'HP', category: 'Office Stationery', price: 1100 },
  { code: 'IT-034', name: 'Heavy Duty Safety Helmet', brand: '3M', category: 'Safety Gear', price: 480 },
  { code: 'IT-035', name: 'Structural Steel I-Beam', brand: 'Tata Steel', category: 'Raw Materials', price: 8200 },
  { code: 'IT-036', name: 'LED Panel Light 15W', brand: 'Philips', category: 'Electrical Supplies', price: 380 },
  { code: 'IT-037', name: 'PVC Pipe Elbow 90 Deg 1"', brand: 'Supreme', category: 'Plumbing Parts', price: 22 },
  { code: 'IT-038', name: 'Flexible Hose Pipe 10m', brand: 'Supreme', category: 'Plumbing Parts', price: 450 },
  { code: 'IT-039', name: 'Combination Spanner Set', brand: 'Bosch', category: 'Hardware & Tools', price: 1650 },
  { code: 'IT-040', name: 'Copper Lug 35 sqmm Pack of 20', brand: 'Anchor', category: 'Electrical Supplies', price: 340 },
  { code: 'IT-041', name: 'Cordless Screwdriver 3.6V', brand: 'Bosch', category: 'Hardware & Tools', price: 2100 },
  { code: 'IT-042', name: 'Overload Relay 9-13A', brand: 'Schneider', category: 'Electrical Supplies', price: 780 },
  { code: 'IT-043', name: 'Highlighter Pen Set of 5', brand: 'HP', category: 'Office Stationery', price: 150 },
  { code: 'IT-044', name: 'First Aid Kit Wall Mount', brand: '3M', category: 'Safety Gear', price: 1400 },
  { code: 'IT-045', name: 'Steel Plate 6mm Thick', brand: 'Tata Steel', category: 'Raw Materials', price: 4500 },
  { code: 'IT-046', name: 'LED Street Light 100W', brand: 'Philips', category: 'Electrical Supplies', price: 3800 },
  { code: 'IT-047', name: 'PVC Pipe Tee 1 Inch', brand: 'Supreme', category: 'Plumbing Parts', price: 28 },
  { code: 'IT-048', name: 'Brass Bib Cock Tap', brand: 'Supreme', category: 'Plumbing Parts', price: 320 },
  { code: 'IT-049', name: 'Safety Harness Double Lanyard', brand: '3M', category: 'Safety Gear', price: 2200 },
  { code: 'IT-050', name: 'Exhaust Fan 12-Inch', brand: 'Philips', category: 'Electrical Supplies', price: 1750 },
  { code: 'IT-051', name: 'Claw Hammer 16oz', brand: 'Bosch', category: 'Hardware & Tools', price: 490 },
  { code: 'IT-052', name: 'Contactor 3-Pole 25A', brand: 'Schneider', category: 'Electrical Supplies', price: 1250 },
  { code: 'IT-053', name: 'Keyboard USB Wired', brand: 'HP', category: 'Office Stationery', price: 450 },
  { code: 'IT-054', name: 'Hand Sanitizer Gel 5L', brand: '3M', category: 'Safety Gear', price: 750 },
  { code: 'IT-055', name: 'Welding Electrode Box 2.5mm', brand: 'Tata Steel', category: 'Raw Materials', price: 620 },
  { code: 'IT-056', name: 'LED Downlight 7W', brand: 'Philips', category: 'Electrical Supplies', price: 220 },
  { code: 'IT-057', name: 'CPVC Union 1 Inch', brand: 'Supreme', category: 'Plumbing Parts', price: 110 },
  { code: 'IT-058', name: 'Waste Coupling Brass', brand: 'Supreme', category: 'Plumbing Parts', price: 180 },
  { code: 'IT-059', name: 'Adjustable Wrench 10"', brand: 'Bosch', category: 'Hardware & Tools', price: 650 },
  { code: 'IT-060', name: '3-Pin Power Plug 16A Pack of 5', brand: 'Anchor', category: 'Electrical Supplies', price: 190 },
  { code: 'IT-061', name: 'Hot Air Gun 1800W', brand: 'Bosch', category: 'Hardware & Tools', price: 2950 },
  { code: 'IT-062', name: 'Miniature Relay 24V DC', brand: 'Schneider', category: 'Electrical Supplies', price: 160 },
  { code: 'IT-063', name: 'A3 Drawing Sheets Pack of 100', brand: 'HP', category: 'Office Stationery', price: 380 },
  { code: 'IT-064', name: 'Safety Shoes Steel Toe', brand: '3M', category: 'Safety Gear', price: 1850 },
  { code: 'IT-065', name: 'MS Angle Bar 50x50x5mm', brand: 'Tata Steel', category: 'Raw Materials', price: 1450 },
  { code: 'IT-066', name: 'LED Bulkhead Fitting 10W', brand: 'Philips', category: 'Electrical Supplies', price: 480 },
  { code: 'IT-067', name: 'PVC End Cap 1 Inch', brand: 'Supreme', category: 'Plumbing Parts', price: 12 },
  { code: 'IT-068', name: 'PTMT Plastic Faucet Tap', brand: 'Supreme', category: 'Plumbing Parts', price: 140 },
  { code: 'IT-069', name: 'Welding Hand Shield Helmet', brand: '3M', category: 'Safety Gear', price: 850 },
  { code: 'IT-070', name: 'Extension Spike Guard 4-Socket', brand: 'Anchor', category: 'Electrical Supplies', price: 480 },
  { code: 'IT-071', name: 'Spirit Level 30cm', brand: 'Bosch', category: 'Hardware & Tools', price: 540 },
  { code: 'IT-072', name: 'Current Transformer 100/5A', brand: 'Schneider', category: 'Electrical Supplies', price: 380 },
  { code: 'IT-073', name: 'Sticky Notes Pad Pack of 6', brand: 'HP', category: 'Office Stationery', price: 180 },
  { code: 'IT-074', name: 'Face Shield Clear Acrylic', brand: '3M', category: 'Safety Gear', price: 250 },
  { code: 'IT-075', name: 'Mild Steel Flat Bar 25x3mm', brand: 'Tata Steel', category: 'Raw Materials', price: 340 },
  { code: 'IT-076', name: 'T5 LED Batten 18W', brand: 'Philips', category: 'Electrical Supplies', price: 210 },
  { code: 'IT-077', name: 'PVC Pipe Nipple 6 Inch', brand: 'Supreme', category: 'Plumbing Parts', price: 35 },
  { code: 'IT-078', name: 'CPVC Ball Valve 1"', brand: 'Supreme', category: 'Plumbing Parts', price: 160 },
  { code: 'IT-079', name: 'Heavy Duty Pipe Wrench 12"', brand: 'Bosch', category: 'Hardware & Tools', price: 1100 },
  { code: 'IT-080', name: 'Ceiling Fan 1200mm Super Speed', brand: 'Philips', category: 'Electrical Supplies', price: 2400 },
  { code: 'IT-081', name: 'Hex Allen Key Set 9pcs', brand: 'Bosch', category: 'Hardware & Tools', price: 380 },
  { code: 'IT-082', name: 'Push Button Green (NO)', brand: 'Schneider', category: 'Electrical Supplies', price: 120 },
  { code: 'IT-083', name: 'Gel Ink Pens Box of 10', brand: 'HP', category: 'Office Stationery', price: 120 },
  { code: 'IT-084', name: 'Fire Extinguisher ABC Pow. 2kg', brand: '3M', category: 'Safety Gear', price: 1650 },
  { code: 'IT-085', name: 'Structural Steel C-Channel', brand: 'Tata Steel', category: 'Raw Materials', price: 3900 },
  { code: 'IT-086', name: 'Halogen Bulb 500W', brand: 'Philips', category: 'Electrical Supplies', price: 120 },
  { code: 'IT-087', name: 'PVC Pipe Collar 1 Inch', brand: 'Supreme', category: 'Plumbing Parts', price: 18 },
  { code: 'IT-088', name: 'Towel Ring Chrome Plated', brand: 'Supreme', category: 'Plumbing Parts', price: 420 },
  { code: 'IT-089', name: 'Cold Chisel 8-Inch', brand: 'Bosch', category: 'Hardware & Tools', price: 210 },
  { code: 'IT-090', name: 'Limit Switch Roller Lever', brand: 'Schneider', category: 'Electrical Supplies', price: 650 },
  { code: 'IT-091', name: 'Jigsaw 450W Professional', brand: 'Bosch', category: 'Hardware & Tools', price: 3400 },
  { code: 'IT-092', name: 'Buzzer 230V AC Panel Mount', brand: 'Schneider', category: 'Electrical Supplies', price: 240 },
  { code: 'IT-093', name: 'Whiteboard Eraser Magnetic', brand: 'HP', category: 'Office Stationery', price: 80 },
  { code: 'IT-094', name: 'Anti-Slip Safety Tape 5m', brand: '3M', category: 'Safety Gear', price: 320 },
  { code: 'IT-095', name: 'MS Square Pipe 25x25mm', brand: 'Tata Steel', category: 'Raw Materials', price: 1100 },
  { code: 'IT-096', name: 'LED Spot Light 3W', brand: 'Philips', category: 'Electrical Supplies', price: 160 },
  { code: 'IT-097', name: 'Brass Union Pipe Joint 1"', brand: 'Supreme', category: 'Plumbing Parts', price: 340 },
  { code: 'IT-098', name: 'Paper Shredder Machine', brand: 'HP', category: 'Office Stationery', price: 5400 },
  { code: 'IT-099', name: 'Steel Toe Gumboots Waterproof', brand: '3M', category: 'Safety Gear', price: 980 },
  { code: 'IT-100', name: 'Rotary Hammer Drill 800W', brand: 'Bosch', category: 'Hardware & Tools', price: 6200 },
];
